### ISSUE TITLE
Checkpoint 3

### ISSUE THREAD

**Issue by cdmckinley** [cdmckinley/splatspot-interface-java#7]
@pawaitemadisoncollege Checkpoint 3 is *almost* ready for review

I've added Cognito to my application, and the web application now uses the database. It now displays user data when the user clicks their username in the upper corner, and provides a form to allow them to change most of their information/configuration. Linking a Discord account is not yet supported. I believe all I have left is the deploy process.

I'm glad to be studying Cognito, data access, and deploying my code.

I'd love to learn better error handling practices though. My project doesn't yet verify its data on the client, and needs more work on server-side verification. And part of what's slowed by down has been not being sure how much data to or not to send to the user, which led me to making a pretty generic error page. I should probably be slightly more specific on the front-end, but I'm not sure how much. (Edit: I just added to my TODO list to work more on JavaDocs in the near future)

There's still much to discuss here, but I thought I'd begin the submission process, let you see my work so far, fix anything I need to, and after all that I can deploy.

My resources are in the journal, but I'll share a few notable resources:
- Oracle's JavaDocs. Both SE and EE (for `javax` package)
- AWS documentation, mostly for Cognito
- W3Schools
- StackOverflow
- Bootstrap documentation
- JavaTPoint and Tutorialspoint

**Comment by pawaitemadisoncollege** [comment]
Excellent progress @cdmckinley! You are right, the next step to finish checkpoint 3 is to deploy to AWS and share the working link with me. 

I did take a bit of time to review your code in its current state. My findings are below:

Excellent use of properties to externalize values to avoid hard-coding of sensitive values or those that may change.  Keen attention to error handling at this stage of the dev process indicates user experience is important to you; often this is an afterthought. JSPs make good use of includes to avoid redundant code. Things are looking good so far!

- [ ] Is it possible to check for null and then do the redirect if the object is null, rather than relying on the exception? Generally with run time exceptions like this, it's best to prevent it from happening in the first place: https://github.com/cdmckinley/splatspot-interface-java/blob/b71877e8ce43e0b97bca74121e35a77612c9ded3/src/main/java/net/splatspot/controller/Profile.java#L30-L50. 
- [ ] I haven't seen the deployed version of this so I may be misunderstanding this portion: in profile.jsp, it seems like the current values are listed in one location and then there's a separate part to change the values. Could these be combined such that the current values are displayed as selected in the preferences area where the user can change them? 

Looking forward to seeing this out on aws so I can play with it a bit!
